#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-java-xmlbuilder
Version  : 0.4
Release  : 1
URL      : https://github.com/jmurty/java-xmlbuilder/archive/v0.4.tar.gz
Source0  : https://github.com/jmurty/java-xmlbuilder/archive/v0.4.tar.gz
Source1  : https://repo1.maven.org/maven2/com/jamesmurty/utils/java-xmlbuilder/0.4/java-xmlbuilder-0.4.jar
Source2  : https://repo1.maven.org/maven2/com/jamesmurty/utils/java-xmlbuilder/0.4/java-xmlbuilder-0.4.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-java-xmlbuilder-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-java-xmlbuilder package.
Group: Data

%description data
data components for the mvn-java-xmlbuilder package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/jamesmurty/utils/java-xmlbuilder/0.4
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/jamesmurty/utils/java-xmlbuilder/0.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/jamesmurty/utils/java-xmlbuilder/0.4
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/jamesmurty/utils/java-xmlbuilder/0.4


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/jamesmurty/utils/java-xmlbuilder/0.4/java-xmlbuilder-0.4.jar
/usr/share/java/.m2/repository/com/jamesmurty/utils/java-xmlbuilder/0.4/java-xmlbuilder-0.4.pom
